# DBMS Lab Assignment



In [1]:
! pip install -r requirements.txt 

In [2]:
import sqlalchemy
sqlalchemy.create_engine('sqlite:///dbms_lab_assginment.db')


Engine(sqlite:///dbms_lab_assginment.db)

In [3]:
%load_ext sql
%sql sqlite:///dbms_lab_assginment.db

In [4]:
%%sql 
CREATE TABLE Employee (
    Emp_id  varchar2(5) PRIMARY KEY,                         
    F_Name varchar2(15) NOT NULL,
    L_Name varchar2(15) NOT NULL, 
    city varchar(10),
    Gender char(1) ,                                                 
    Emp_hire_date  date,
    Job_code varchar(5),
    Supervisor_id  varchar(5),
    Dept_no number(4),
    CONSTRAINT CHK_gender CHECK (Gender IN ('M', 'm', 'F', 'f')),
    CONSTRAINT FK_SupervisorID FOREIGN KEY (Supervisor_id)
    REFERENCES Employee(Emp_id),
    CONSTRAINT FK_DeptNo FOREIGN KEY (Dept_no)
    REFERENCES Department(Dept_no)
);

* sqlite:///dbms_lab_assginment.db
Done.


[]

In [5]:
%%sql 
CREATE TABLE Department (
     DepNo number(4) PRIMARY KEY,
     DName varchar(15),
     Mgr_id char(9) NOT NULL,
     CONSTRAINT U_deptName UNIQUE (DName),
     CONSTRAINT FK_MgrID FOREIGN KEY (Mgr_id)
     REFERENCES Employee(Emp_id)

);

* sqlite:///dbms_lab_assginment.db
Done.


[]

In [6]:
%%sql 
CREATE TABLE Project(
    PNumber number(5) PRIMARY KEY,
    PName varchar(15) NOT NULL,
    DepNo number(4),
    CONSTRAINT FK_DepNum FOREIGN KEY (DepNo)
    REFERENCES Department(DepNo) 
);

* sqlite:///dbms_lab_assginment.db
Done.


[]

In [7]:
%%sql 
CREATE TABLE Works_on (
    PNo number(5),
    emp_id varchar(5),
    CONSTRAINT FK_empID FOREIGN KEY (emp_id)
    REFERENCES Employee(Emp_id),
    CONSTRAINT FK_prjtnum FOREIGN KEY (PNo)
    REFERENCES Project(PNumber)
);

* sqlite:///dbms_lab_assginment.db
Done.


[]

In [8]:
%%sql 
CREATE TABLE Dependent (
     Emp_id varchar(5) PRIMARY KEY,
     Dependent_Name varchar(15) NOT NULL,                      
     Gender char(1), 
     CONSTRAINT CHK_gender CHECK (Gender IN ('M', 'm', 'F', 'f')),
     CONSTRAINT FK_empID FOREIGN KEY (emp_id)
     REFERENCES Employee(Emp_id)
);

* sqlite:///dbms_lab_assginment.db
Done.


[]

In [9]:
%%sql 
INSERT INTO Employee
('Emp_id','F_Name','L_Name','city','Gender','Emp_hire_date','Job_code','Supervisor_id','Dept_no')
VALUES
(888665555,'Saahil','Ali','Indore','M','2018-08-08','INTRN','NA',29),
(502,'William','SmithField','NYC','M','2004-06-22','502','NA',44),
(503,'Rebeca','Black','Manhattan','F','2017-12-09','502','NA',65),
(5,'Jada','Facer','Houston','F','2000-05-15','682','NA',508),
(504,'John','Corner','Houston','M','2001-02-15','682','5',508),
(505,'Maria','Smith','Houston','F','2005-07-10','897','5',508);


* sqlite:///dbms_lab_assginment.db
6 rows affected.


[]

In [10]:
%%sql
SELECT * FROM Employee 

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29),
 ('502', 'William', 'SmithField', 'NYC', 'M', '2004-06-22', '502', 'NA', 44),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508)]

In [11]:
%%sql 
INSERT INTO Department
('DepNo','DName','Mgr_id')
VALUES 
(29,'InternsDept','888665555'),
(44,'Management','502'),
(65,'Logistics','503'),
(508,'Marketting','5');
     

* sqlite:///dbms_lab_assginment.db
4 rows affected.


[]

In [12]:
%%sql 
SELECT * FROM Department

* sqlite:///dbms_lab_assginment.db
Done.


[(29, 'InternsDept', '888665555'),
 (44, 'Management', '502'),
 (65, 'Logistics', '503'),
 (508, 'Marketting', '5')]

In [13]:
%%sql 
INSERT INTO Project
('PNumber','PName','DepNo')
VALUES
(3388,'ProjectF',29),
(1945,'Manage',44),
(5465,'Shipit',65),
(4578,'Sellit',508);     

* sqlite:///dbms_lab_assginment.db
4 rows affected.


[]

In [14]:
%%sql 
SELECT * FROM Project

* sqlite:///dbms_lab_assginment.db
Done.


[(3388, 'ProjectF', 29),
 (1945, 'Manage', 44),
 (5465, 'Shipit', 65),
 (4578, 'Sellit', 508)]

In [15]:
%%sql 
INSERT INTO  Works_on 
('PNo', 'emp_id')
VALUES
(4578,'5'),
(3388,'888665555'),
(1945,'502'),
(5465,'503'),
(4578,'504'),
(4578,'505');    

* sqlite:///dbms_lab_assginment.db
6 rows affected.


[]

In [16]:
%%sql 
SELECT * FROM Works_on

* sqlite:///dbms_lab_assginment.db
Done.


[(4578, '5'),
 (3388, '888665555'),
 (1945, '502'),
 (5465, '503'),
 (4578, '504'),
 (4578, '505')]

In [17]:
%%sql 
INSERT INTO Dependent 
('Emp_id','Dependent_Name','Gender')
VALUES
('5','Aaron Facer','M'),
('888665555','Naazneen Ali','F'),
('502','Robin SmithField','M'),
('503','Kurtz Black','M'),
('504','Sarah Corner','F'),
('505','Will Smith','M');       

* sqlite:///dbms_lab_assginment.db
6 rows affected.


[]

In [18]:
%%sql 
SELECT * FROM Dependent

* sqlite:///dbms_lab_assginment.db
Done.


[('5', 'Aaron Facer', 'M'),
 ('888665555', 'Naazneen Ali', 'F'),
 ('502', 'Robin SmithField', 'M'),
 ('503', 'Kurtz Black', 'M'),
 ('504', 'Sarah Corner', 'F'),
 ('505', 'Will Smith', 'M')]

3. Write the SQL code to change the job code to 501 for the person whose emp_id is'888665555'. After you have completed the task, examine the results, and then reset the job code to its original value.

In [19]:
%%sql 
UPDATE Employee
SET Job_code = '501'
WHERE Emp_id=888665555;
SELECT * FROM Employee

* sqlite:///dbms_lab_assginment.db
1 rows affected.
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', '501', 'NA', 29),
 ('502', 'William', 'SmithField', 'NYC', 'M', '2004-06-22', '502', 'NA', 44),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508)]

In [20]:
%%sql 
UPDATE Employee
SET Job_code = 'INTRN'
WHERE Emp_id = 888665555;

* sqlite:///dbms_lab_assginment.db
1 rows affected.


[]

4. Write the SQL code that lists all details of employees with a job code of 502. 

In [21]:
%%sql
SELECT * FROM Employee
WHERE Job_code = 502 ;

* sqlite:///dbms_lab_assginment.db
Done.


[('502', 'William', 'SmithField', 'NYC', 'M', '2004-06-22', '502', 'NA', 44),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65)]

5. Write the SQL code to delete the row for the person named William Smithfield, who was hired on June 22, 2004, and whose job code classification is 502. (Hint: Use logical operators to include all the information given in this problem.) 

In [22]:
%%sql 
DELETE FROM Employee 
WHERE Job_code = 502 AND 
Emp_hire_date='2004-06-22' AND 
F_Name = 'William' AND 
L_Name = 'SmithField';
SELECT * FROM Employee

* sqlite:///dbms_lab_assginment.db
1 rows affected.
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508)]

6. List the names of all employees who work in department 508. 

In [23]:
%%sql 
SELECT F_Name,L_Name FROM Employee
WHERE Dept_no = 508 ;

* sqlite:///dbms_lab_assginment.db
Done.


[('Jada', 'Facer'), ('John', 'Corner'), ('Maria', 'Smith')]

7. Add a new column named salary in employee table.

In [24]:
%%sql
ALTER TABLE Employee
ADD Salary number(10) ;
SELECT * FROM Employee

* sqlite:///dbms_lab_assginment.db
Done.
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29, None),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65, None),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508, None),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508, None),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508, None)]

In [25]:
%%sql
UPDATE Employee
SET Salary = 25000
WHERE Emp_id = 888665555 ;
UPDATE Employee
SET Salary = 35000
WHERE Emp_id = 503 ;
UPDATE Employee
SET Salary = 100000
WHERE Emp_id = 5 ;
UPDATE Employee
SET Salary = 90000
WHERE Emp_id = 504 ;
UPDATE Employee
SET Salary = 49000
WHERE Emp_id = 505 ;

* sqlite:///dbms_lab_assginment.db
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.


[]

8. List names and salaries of all employee ordered by salary.

In [26]:
%%sql 
SELECT F_Name,Salary FROM Employee
ORDER BY Salary ASC;

* sqlite:///dbms_lab_assginment.db
Done.


[('Saahil', 25000),
 ('Rebeca', 35000),
 ('Maria', 49000),
 ('John', 90000),
 ('Jada', 100000)]

9. List the name of employees whose salary is between 30000 and 50000.

In [27]:
%%sql 
SELECT F_Name FROM Employee
WHERE Salary BETWEEN 30000 AND 50000

* sqlite:///dbms_lab_assginment.db
Done.


[('Rebeca',), ('Maria',)]

10. List the name of employees who lives in Houston.

In [28]:
%%sql 
SELECT F_Name FROM Employee
WHERE city='Houston'

* sqlite:///dbms_lab_assginment.db
Done.


[('Jada',), ('John',), ('Maria',)]

11. List department number and number of employees in each department, ordered by number of employees in each department

In [29]:
%%sql 
SELECT count(*) AS num_employees, dept.DepNo 
from Employee AS emp 
INNER JOIN Department AS dept ON emp.Dept_no = dept.DepNo 
GROUP BY dept.DepNo
ORDER BY num_employees

* sqlite:///dbms_lab_assginment.db
Done.


[(1, 29), (1, 65), (3, 508)]

12. List department number and number of employees in departments that have more than 2 employees, ordered by department number. 


In [30]:
%%sql 
SELECT count(*) AS num_employees, dept.DepNo 
from Employee AS emp 
INNER JOIN Department AS dept ON emp.Dept_no = dept.DepNo 
GROUP BY dept.DepNo
HAVING num_employees > 2

* sqlite:///dbms_lab_assginment.db
Done.


[(3, 508)]

13. List the emp_id of employees who works on project 3388 or project 1945.

In [31]:
%%sql 
SELECT emp_id FROM Works_on
WHERE PNo = 3388 OR PNo = 1945

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555',), ('502',)]

14. List department with their manager name

In [32]:
%%sql 
SELECT dept.DName, emp.F_Name
FROM Department as dept 
INNER JOIN Employee as emp 
ON dept.Mgr_id = emp.Emp_id

* sqlite:///dbms_lab_assginment.db
Done.


[('InternsDept', 'Saahil'), ('Logistics', 'Rebeca'), ('Marketting', 'Jada')]

15. List the name of all female employees. 

In [33]:
%%sql 
SELECT F_Name,L_Name 
FROM Employee 
WHERE Gender='F';

* sqlite:///dbms_lab_assginment.db
Done.


[('Rebeca', 'Black'), ('Jada', 'Facer'), ('Maria', 'Smith')]

16. List the first name of all employee whose last name begins with letter ‘sm’ 

In [34]:
%%sql 
SELECT F_Name
FROM Employee 
WHERE L_Name LIKE "sm%"

* sqlite:///dbms_lab_assginment.db
Done.


[('Maria',)]

17. Find the total no of departments. 

In [35]:
%%sql 
SELECT count(DepNo)
FROM Department

* sqlite:///dbms_lab_assginment.db
Done.


[(4,)]

18. Find the name of senior most employee

In [36]:
%%sql 
SELECT F_name , Emp_hire_date
FROM Employee
ORDER BY Emp_hire_date ASC
LIMIT 1

* sqlite:///dbms_lab_assginment.db
Done.


[('Jada', '2000-05-15')]

19. Display from the Employees table the first name (fname), last name (lname), employeeID(emp_id) and job code (Job_code) columns for those employees with a job code greater than 200; and rename the column headings to:  “First Name,” “Last Name,” “IDENTIFICATION#” and “Job Level.”

In [37]:
%%sql 
SELECT Emp_id, F_name, L_name, Job_code
FROM Employee
WHERE Job_code > 200;

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'INTRN'),
 ('503', 'Rebeca', 'Black', '502'),
 ('5', 'Jada', 'Facer', '682'),
 ('504', 'John', 'Corner', '682'),
 ('505', 'Maria', 'Smith', '897')]

In [38]:
%%sql
ALTER TABLE Employee
RENAME COLUMN F_Name TO "First Name";
ALTER TABLE Employee
RENAME COLUMN L_Name TO "Last Name";
ALTER TABLE Employee
RENAME COLUMN Emp_id TO "IDENTIFICATION#";
ALTER TABLE Employee
RENAME COLUMN Job_code TO "Job Level";

* sqlite:///dbms_lab_assginment.db
Done.
Done.
Done.
Done.


[]

In [39]:
%%sql
SELECT * FROM Employee

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29, 25000),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65, 35000),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508, 100000),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508, 90000),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508, 49000)]

20. Show all the different projects for which employee work. Display only projects in which more than four employees are employed.

In [40]:
%%sql
SELECT PName FROM Project 

* sqlite:///dbms_lab_assginment.db
Done.


[('ProjectF',), ('Manage',), ('Shipit',), ('Sellit',)]

In [41]:
%%sql 
SELECT dept.DName
FROM Employee AS emp
INNER JOIN Department AS dept
ON emp.Dept_no = dept.DepNo
GROUP BY dept.DName
HAVING COUNT(*) > 4;

* sqlite:///dbms_lab_assginment.db
Done.


[]

21. Find emp_id of all employees working in the project in department named research

In [42]:
%%sql
SELECT "IDENTIFICATION#"
FROM Employee 
WHERE Dept_no =(SELECT DepNo
                FROM Department
                WHERE DName='research')	

* sqlite:///dbms_lab_assginment.db
Done.


[]

22. List employees who joined on the date on which ‘john’ joined.

In [43]:
%%sql
SELECT "First Name" 
FROM Employee
WHERE Emp_hire_date = (SELECT Emp_hire_date
                       FROM Employee 
                       WHERE "First Name"="John")
AND "IDENTIFICATION#" != (SELECT "IDENTIFICATION#"
                       FROM Employee 
                       WHERE "First Name"="John")

* sqlite:///dbms_lab_assginment.db
Done.


[]

23. Find the emp_id who works on project named ‘projectF’ 

In [44]:
%%sql 
SELECT emp_id 
FROM Works_on 
WHERE PNo = (SELECT PNumber 
             FROM Project 
             WHERE PName = "ProjectF")

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555',)]

24. List the name of female dependents of employee named ‘maria’ 

In [45]:
%%sql
SELECT Dependent_Name
FROM  Dependent
WHERE Gender = 'F'  
AND   Emp_id = (SELECT "IDENTIFICATION#" 
                FROM Employee
                WHERE "First Name" = "Maria") 

* sqlite:///dbms_lab_assginment.db
Done.


[]

25. Execute query 23 using join. 

In [46]:
%%sql
SELECT emp."IDENTIFICATION#" 
FROM Employee AS emp
INNER JOIN Project AS prjt
ON emp.Dept_no = prjt.DepNo
WHERE prjt.PName="ProjectF"

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555',)]

26. List employee details along with their dependent’s details(use join)

In [47]:
%%sql 
SELECT emp.*, dpndnt.Dependent_Name , dpndnt.Gender AS Dependent_Gender
FROM Employee AS emp
INNER JOIN Dependent AS dpndnt
ON emp."IDENTIFICATION#" = dpndnt.Emp_id


* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29, 25000, 'Naazneen Ali', 'F'),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65, 35000, 'Kurtz Black', 'M'),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508, 100000, 'Aaron Facer', 'M'),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508, 90000, 'Sarah Corner', 'F'),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508, 49000, 'Will Smith', 'M')]

27. List employee details along with their dependent’s details and also include  employees those do not have dependents

In [48]:
%%sql 
SELECT emp.*, dpndnt.Dependent_Name , dpndnt.Gender AS Dependent_Gender
FROM Employee AS emp
FULL JOIN Dependent AS dpndnt
ON emp."IDENTIFICATION#" = dpndnt.Emp_id

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29, 25000, 'Naazneen Ali', 'F'),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65, 35000, 'Kurtz Black', 'M'),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508, 100000, 'Aaron Facer', 'M'),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508, 90000, 'Sarah Corner', 'F'),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508, 49000, 'Will Smith', 'M')]

28. List employees with their supervisor name.

In [49]:
%%sql 
SELECT emp."First Name" AS "Employee Name", sup."First Name" AS "Supervisor Name"
FROM Employee AS emp 
JOIN Employee AS sup 
ON emp."Supervisor_id" = sup."IDENTIFICATION#"

* sqlite:///dbms_lab_assginment.db
Done.


[('John', 'Jada'), ('Maria', 'Jada')]

29. Change the name of table employee to employee_details 

In [50]:
%%sql
ALTER TABLE Employee
RENAME TO Employee_details;

* sqlite:///dbms_lab_assginment.db
Done.


[]

30. List the name of employees who doesn't has supervisor

In [51]:
%%sql 
SELECT "First Name" 
FROM Employee_details
WHERE Supervisor_id = "NA"

* sqlite:///dbms_lab_assginment.db
Done.


[('Saahil',), ('Rebeca',), ('Jada',)]

31. Increase salary of employee with emp_id 5 by 10%

In [52]:
%%sql 
UPDATE Employee_details
SET Salary = 1.1 * Salary
WHERE "IDENTIFICATION#"=5;

* sqlite:///dbms_lab_assginment.db
1 rows affected.


[]

In [53]:
%%sql
SELECT * FROM Employee_details ;

* sqlite:///dbms_lab_assginment.db
Done.


[('888665555', 'Saahil', 'Ali', 'Indore', 'M', '2018-08-08', 'INTRN', 'NA', 29, 25000),
 ('503', 'Rebeca', 'Black', 'Manhattan', 'F', '2017-12-09', '502', 'NA', 65, 35000),
 ('5', 'Jada', 'Facer', 'Houston', 'F', '2000-05-15', '682', 'NA', 508, 110000.00000000001),
 ('504', 'John', 'Corner', 'Houston', 'M', '2001-02-15', '682', '5', 508, 90000),
 ('505', 'Maria', 'Smith', 'Houston', 'F', '2005-07-10', '897', '5', 508, 49000)]

32. Delete all the tables. 

In [54]:
%%sql
DROP TABLE Employee_details;
DROP TABLE Department;
DROP TABLE Project;
DROP TABLE Works_on;
DROP TABLE Dependent;

* sqlite:///dbms_lab_assginment.db
Done.
Done.
Done.
Done.
Done.


[]